image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Android Development Environment
    init: |
      # 安装Android SDK
      export ANDROID_HOME="$HOME/android-sdk"
      mkdir -p $ANDROID_HOME
      cd $ANDROID_HOME
      
      # 下载命令行工具
      wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      unzip -q commandlinetools-linux-9477386_latest.zip
      
      # 创建正确目录结构
      mkdir -p cmdline-tools/latest
      mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
      rm commandlinetools-linux-9477386_latest.zip
      
      # 设置环境变量
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      
      # 接受许可证并安装SDK组件
      yes | sdkmanager --licenses >/dev/null 2>&1
      sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" >/dev/null 2>&1
      
      # 创建local.properties
      echo "sdk.dir=$ANDROID_HOME" > /workspace/CameraX/local.properties
      
      echo "Android SDK setup completed!"
    
    command: |
      export ANDROID_HOME="$HOME/android-sdk"
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      echo "Ready for Android development!"
      echo "ANDROID_HOME: $ANDROID_HOME"

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - fwcd.kotlin